import argparse
import json
import os
import sys
import time
from typing import Literal
import boto3
from pydantic import BaseModel, Field
from strands import Agent
from strands.models.bedrock import BedrockModel

# Which model family to use, and the env var holding its Bedrock model ID (plus its default).
# All are called through Bedrock's Converse API, so the same BedrockModel class serves each one.
PROVIDERS = {
    "anthropic": ("STRANDS_MODEL_ID_ANTHROPIC", "global.anthropic.claude-sonnet-5"),
    "openai": ("STRANDS_MODEL_ID_OPENAI", "openai.gpt-oss-120b-1:0"),  # OpenAI's open-weight gpt-oss
    "amazon": ("STRANDS_MODEL_ID_AMAZON", "global.amazon.nova-2-lite-v1:0"),  # Amazon's own Nova
}


# --- Structured output: the agent must reply with an object matching this schema ---
# Field descriptions are sent to the model, so they double as instructions for each field.

class ItineraryReview(BaseModel):
    is_realistic: bool = Field(description="Whether the plan can be done at a relaxed pace in one day")
    crowd_risk: Literal["low", "medium", "high"] = Field(description="How crowded the chosen places and times are likely to be")
    nature_score: int = Field(description="How nature-focused the plan is, from 1 (not at all) to 10 (entirely)")
    issues: list[str] = Field(description="Specific problems with the plan, one short sentence each")
    suggested_fix: str = Field(description="One concrete change that would improve the plan the most")


# A deliberately bad plan: rushed, crowded, and barely any nature
SAMPLE_ITINERARY = """
Saturday in Tokyo, relaxed nature day:
- 8:00 Shibuya Crossing and Hachiko for photos
- 9:30 Senso-ji and Nakamise Street
- 11:00 Day trip to Mount Fuji 5th Station
- 15:00 Tokyo Disneyland
- 20:00 Robot show in Shinjuku, then karaoke until late
""".strip()


PLAN_FORMAT = "Reply with a title line and 5 or 6 timed bullet points only."

# Planner agents that can write a fresh itinerary to review: name -> system prompt
PLANNERS = {
    "chaotic": (
        "You write Tokyo day plans that claim to be a relaxed nature day but are really overpacked, "
        f"visit famous crowded spots at peak times, and contain almost no nature. {PLAN_FORMAT}"
    ),
    "thoughtful": (
        "You write genuinely relaxed, nature-focused Tokyo day plans: gardens, parks and easy hikes, "
        "few stops close together, quiet times of day, and realistic travel time between them. "
        f"{PLAN_FORMAT}"
    ),
    "offbeat": (
        "You write relaxed, nature-focused Tokyo day plans that go off the beaten path: lesser-known gardens, "
        "neighborhood shrines, river walks and green spaces most tourists skip, avoiding famous landmarks. "
        f"Name real places and add a few words on why each is special. {PLAN_FORMAT}"
    ),
}


def get_itinerary(planner: str | None, model: BedrockModel) -> tuple[str, str]:
    """Return the itinerary to review and a label saying where it came from."""
    if planner is None:
        return SAMPLE_ITINERARY, "built-in sample; use --planner for a fresh one"
    # A plain text planner agent (no structured_output_model) writes a fresh itinerary
    planner_agent = Agent(name=f"{planner.title()} Planner", model=model, system_prompt=PLANNERS[planner],
                          callback_handler=None)
    print(f"Generating an itinerary with {planner_agent.name}...\n")
    return str(planner_agent("Write today's plan.")).strip(), f"generated by {planner_agent.name}"


def print_steps(messages: list[dict]) -> None:
    """Print what happened after the prompt: each text reply, tool call and tool result, in order."""
    for message in messages[1:]:
        for block in message["content"]:
            if "text" in block and block["text"].strip():
                label = "Model said" if message["role"] == "assistant" else "Strands asked"
                print(f"* {label}: {block['text'].strip()}")
            elif "toolUse" in block:
                print(f"* Model called {block['toolUse']['name']}({', '.join(block['toolUse']['input'])})")
            elif "toolResult" in block:
                text = " ".join(part.get("text", "") for part in block["toolResult"]["content"])
                print(f"* Tool result ({block['toolResult']['status']}): {text}")
    print()


def main(planner: str | None):

    # 1. Debug Verification: Print environmental variables loaded by uv
    profile = os.environ.get("AWS_PROFILE", "Not Found")
    region = os.environ.get("AWS_REGION", "Not Found")
    provider = os.environ.get("STRANDS_MODEL_PROVIDER", "anthropic")
    if provider not in PROVIDERS:
        sys.exit(f"STRANDS_MODEL_PROVIDER must be one of {', '.join(PROVIDERS)}, not {provider!r}")
    model_env, default_model_id = PROVIDERS[provider]
    model_id = os.environ.get(model_env, default_model_id)

    print("--- Environment Status ---")
    print(f"Active AWS Profile: {profile}")
    print(f"Active AWS Region:  {region}")
    print(f"Model Provider:     {provider} (STRANDS_MODEL_PROVIDER)")
    print(f"Model ID:           {model_id} ({model_env})")
    print("--------------------------\n")

    model = BedrockModel(
        model_id=model_id,
        boto_session=boto3.Session(profile_name=profile, region_name=region),
    )

    # 2. structured_output_model makes Strands add a tool named after the class, whose input schema
    #    is the model's JSON schema. The agent answers by calling it, and Pydantic validates the call.
    reviewer = Agent(
        name="Itinerary Reviewer",
        model=model,
        system_prompt="You review Tokyo day plans for travelers who want a relaxed, nature-focused day away from crowds.",
        structured_output_model=ItineraryReview,
        callback_handler=None,
    )

    print("--- Agent ---")
    print(f"Name:          {reviewer.name}")
    print(f"System prompt: {reviewer.system_prompt}")
    print(f"Output model:  {ItineraryReview.__name__}\n")

    print("--- Output schema (ItineraryReview.model_json_schema()) ---")
    for field, schema in ItineraryReview.model_json_schema()["properties"].items():
        kind = " | ".join(schema["enum"]) if "enum" in schema else schema["type"]
        print(f"* {field} ({kind}): {schema['description']}")
    print()

    print("--- How Strands gets the object ---")
    print(f"1. It offers the model a tool called {ItineraryReview.__name__}, with the schema above as its input.")
    print("2. Pydantic validates the call. Errors go back to the model as the tool result, so it can retry.")
    print("3. If the model ends without calling the tool, Strands asks again and forces that tool.\n")

    # 3. Get the plan to review: the fixed sample, or a fresh plan written by a planner agent
    itinerary, source = get_itinerary(planner, model)
    print(f"--- Itinerary to review ({source}) ---")
    print(f"{itinerary}\n")

    print(f"Running {reviewer.name} on {model_id} via Amazon Bedrock...\n")
    start = time.perf_counter()
    result = reviewer(itinerary)
    duration = time.perf_counter() - start

    # 4. The tool call is in the conversation like any other, followed by Strands' validation result
    print("--- Steps ---")
    print_steps(reviewer.messages)

    # 5. result.structured_output is an ItineraryReview instance, not a string
    review = result.structured_output
    print(f"--- Result: {type(review).__name__} ---")
    print(json.dumps(review.model_dump(), indent=2))
    print()

    # 6. Because the fields are typed, plain code can act on them without parsing text
    print("--- Using the fields in code ---")
    print(f"review.is_realistic = {review.is_realistic}")
    print(f"review.crowd_risk   = {review.crowd_risk!r}")
    print(f"review.nature_score = {review.nature_score}")
    print(f"len(review.issues)  = {len(review.issues)}\n")

    if review.is_realistic and review.crowd_risk == "low" and review.nature_score >= 7:
        print("Verdict: approve the plan as is.")
    else:
        print(f"Verdict: send back for changes. Top fix: {review.suggested_fix}")

    usage = reviewer.event_loop_metrics.accumulated_usage
    print("\n--- Run Summary ---")
    print(f"Stop reason: {result.stop_reason}")
    print(f"Cycles:      {result.metrics.cycle_count}")
    print(f"Duration:    {duration:.1f}s")
    print(f"Tokens:      {usage['inputTokens']} in, {usage['outputTokens']} out (reviewer only)")

if __name__ == "__main__":
    # Model output contains characters like en dashes that Windows code pages (e.g. cp932) can't encode
    # when output is redirected to a file, so always write UTF-8
    sys.stdout.reconfigure(encoding="utf-8")
    parser = argparse.ArgumentParser(description="Review a Tokyo itinerary with structured output.")
    parser.add_argument("--planner", choices=PLANNERS,
                        help="have a planner agent write a fresh itinerary instead of using the built-in bad sample")
    args = parser.parse_args()
    main(args.planner)
